#!/usr/bin/env node

const util = require('util');
const exec = util.promisify(require('child_process').exec);
const process = require('process');

console.log("hook is running");

const {ESLint} = require("eslint");

(async function main() {
  // 1. Create an instance.
  // @ts-ignore
  const eslint = new ESLint();
  await exec("git stash save -q --keep-index")
  // 2. Lint files.
  const results = await eslint.lintFiles(["./main.js"]);
  await exec("git stash pop")

  // 3. Format the results.
  const formatter = await eslint.loadFormatter("stylish");
  const resultText = formatter.format(results);

  for (let result of results) {
    if(result.errorCount > 0) {
        process.exitCode = 1;
    }
  }
  console.log(results);
  // 4. Output it.
  console.log(resultText);
})().catch((error) => {
  process.exitCode = 1;
  console.error(error);
});